<?php

/**
 * @file
 * Install the things.
 */

/**
 * Implements hook_field_schema().
 */
function imagemapfield_field_schema($field) {
  return array(
    'columns' => array(
      'value' => array(
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
      ),
      'attach_to' => array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => FALSE,
      ),
    ),
  );
}
